version: '3.5'

services:
  database:
    container_name: nestjs-api-example
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=senha #studying purpose use environment variables
      - MYSQL_DATABASE=nestjsapiexample
    volumes:
      - db-volume:/var/lib/mysql
  backend:
    # image: eddcp/nestjs-api-example
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    links: 
      - database
    depends_on: 
      - database

volumes:
  db-volume: